version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/"
  schedule:
    interval: daily
    time: "10:10"
    timezone: Europe/Bucharest
  open-pull-requests-limit: 25
  target-branch: "master"