trigger:
- master

stages:
- stage: build_debug_stage
  displayName: "Build and test in debug mode"
  jobs:
  - job:
    strategy:
      matrix:
        Windows2019:
          imageName: 'windows-2019'
        Windows2022:
          imageName: 'windows-2022'
    pool:
      vmImage: $(imageName)
    steps:
    - checkout: self
      submodules: true
    - task: UseDotNet@2
      displayName: "Install .NET 5"
      inputs:
       version: 5.x
    - task: UseDotNet@2
      displayName: "Install .NET 6"
      inputs:
       version: 6.x
    - task: DotNetCoreCLI@2
      displayName: "Restore NuGet packages"
      inputs:
        command: 'restore'
        projects: "**/*.csproj"
        includeNuGetOrg: true
        verbosityRestore: 'Minimal'
    - task: DotNetCoreCLI@2
      displayName: "Build in Debug"
      inputs:
        command: 'build'
        projects: 'src/IX.StandardExtensions.WPF.sln'
        arguments: '-c Debug'

- stage: build_release_stage
  dependsOn: build_debug_stage
  displayName: "Build in release and create packages"
  jobs:
  - job:
    pool:
      vmImage: 'windows-2022'
    steps:
    - checkout: self
      submodules: true
    - task: DotNetCoreCLI@2
      displayName: 'Build in Release'
      inputs:
        command: 'build'
        projects: 'src/IX.StandardExtensions.WPF.sln'
        arguments: '-c Release --version-suffix alpha.$(Build.BuildNumber)'
    - task: CopyFiles@2
      inputs:
        contents: '**\*.nupkg'
        targetFolder: '$(build.artifactstagingdirectory)'
    - task: CopyFiles@2
      inputs:
        contents: '**\*.snupkg'
        targetFolder: '$(build.artifactstagingdirectory)'
    - task: NuGetAuthenticate@0
      displayName: 'NuGet Authenticate'
    - task: NuGetCommand@2
      displayName: 'NuGet push'
      inputs:
        command: push
        publishVstsFeed: 'IX.Framework/IX.Framework_Beta_Feed'
        allowPackageConflicts: false